# Generated by Django 3.1.3 on 2020-11-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useraccount_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name_plural': 'users'},
        ),
    ]
