# Generated by Django 3.1.3 on 2020-11-08 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201108_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2020, 11, 8, 19, 17, 37, 859985, tzinfo=utc), max_length=150, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
